### PR TITLE
Rate limit disable

### LINKED ISSUE #952: Add ability to turn off rate limiting
I'm using my own MusicBrainz server, and it would be nice to turn off rate limiting. Maybe we could add a new field to the config called `disableRateLimiting` and then add some conditional logic to prevent it from running? or maybe we could allow users to set their own values passed into `RateLimitThreshold`. I think the first option makes more sense as it's simpler, and I can't think of reasons why users would want to slow down requests or speed them up (since they'd hit the limit).

### PR DESCRIPTION
**Pull request by ben-obringer**
Resolves #952

Here's my submission for this issue. Happy to have a conversation about any of these changes and make edits where needed.

- Added a new field to the config called `disableRateLimiting`
- Added a helper function for applying the rate limiter to reduce duplicate logic

**Testing**
- Added test cases for each of the functions where the rate limiter is called (get, post, edit)
  - Each function has tests for the default case when the field is not given (false), when the field is false, and when the field is true
- Added sinon to test whether or not the limiter was called. Also stubbed http requests as the responses aren't relevant to these tests.
- Replaced the construction of `MusicBrainzApi` objects with `IMusicBrainzConfig` objects. I did this so that it was easier to extend the default configs instead of having to create a new type of `MusicBrainzApi` for each config variation.

### CODE REVIEW

**Comment by Borewit** [comment]
I changed `#952` to `Resolves #952`, so that the PR automatically correlates to the issue.

Documentation: [Linking a pull request to an issue using a keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

**Comment by ben-obringer** [comment]
> I changed `#952` to `Resolves #952`, so that the PR automatically correlates to the issue.

Thanks for the tip!

**Comment by Borewit** [comment]
Part of [v0.17.0](https://github.com/Borewit/musicbrainz-api/releases/tag/v0.17.0)

**Comment by ben-obringer** [comment]
> Great work @ben-obringer, unit test documentation, very complete, awesome 👍🏻

Thank you!

**Pull request merged**
